services:
  - type: web
    name: smart-payment-verification
    env: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p templates static
    startCommand: |
      gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 60
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 10000
      - key: DEBUG_MODE
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: FRAUD_THRESHOLD
        value: 0.7
      - key: MAX_VERIFICATION_AGE
        value: 24
      - key: ENABLE_TEST_ENDPOINTS
        value: true
      - key: SUPABASE_URL
        fromDatabase:
          name: supabase-config
          property: connectionString
      - key: SUPABASE_KEY
        fromDatabase:
          name: supabase-config
          property: password
      - key: SMS_FORWARDER_SECRET
        generateValue: true
      - key: SMS_FORWARDER_NUMBER
        value: "+250791646062"
    healthCheckPath: /health
    autoDeploy: false
    region: oregon
